defaultBranch: 'main'
branches:
  - label:
      - bug
      - enhancement
      - maintenance
      - todo
    name: development
    prefix: dev-
    prTarget: development
branchName: '${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
